### ISSUE TITLE
ghoneycutt-nsswitch dependency

### ISSUE THREAD

**Issue by gonrada** [ghoneycutt/puppet-module-pam#112]
Hello,  I was wanting to install your module but it has a dependency 'ghoneycutt-nsswitch' that conflict with a module I am already using. If I don't plan on using your module to update the nsswitch.conf would it be safe to use the "--ignore-dependencies" flag when install your module?

Thanks

**Comment by ghoneycutt** [comment]
The main pam class does a simple include[1] of nsswitch. If you wanted to use another nsswitch module than mine, that would work though you would need some module named nsswitch, even if there was no code in it and it effectively did nothing.

[1] - https://github.com/ghoneycutt/puppet-module-pam/blob/master/manifests/init.pp#L49
