### ISSUE TITLE
pam::service includes pam

### ISSUE THREAD

**Issue by nomadcz** [ghoneycutt/puppet-module-pam#120]
Hello,

Is there a reason pam::service includes pam ? I thought it would manage just /etc/pam.d/service and not the whole pam config.

Thank you and best regards,
Michal

**Comment by ghoneycutt** [comment]
Since none of the variables or resources come from the pam class this should be ok. Could you please send a pull request? You will also need to change the spec test.

https://github.com/ghoneycutt/puppet-module-pam/blob/master/spec/defines/service_spec.rb#L14
change to `should_not`

**Comment by ghoneycutt** [comment]
We have released a new major version of this module and greatly appreciate your efforts. Please consider using the new version which supports Puppet 5 and 6.
