### ISSUE TITLE
Unwanted 'deny all' in allowed_users

### ISSUE THREAD

**Issue by butlerdr** [ghoneycutt/puppet-module-pam#131]
Using this module on Satellite 6, the allowed_users variables automatically adds the following lines:
# default deny
- : ALL : ALL

Formatting for the users and groups I want in there is perfect, but that final line appears anyway unwanted all the time.

Reproducible: always
OS: Red Hat Enterprise Linux 6.7
Puppet master: Red Hat Satellite 6.1.8

**Comment by benkevan** [comment]
Can you describe how it's unwanted? 

Are you saying you want to remove the the DENY declaration?

**Comment by ghoneycutt** [comment]
The default deny is by design as it is the right thing to do from a security perspective. If you would like to make this optional, I'm happy to accept a pull request.
