### ISSUE TITLE
Consistent implementation

### ISSUE THREAD

**Issue by jhg03a** [ghoneycutt/puppet-module-pam#133]
Is there a reason why you take different approaches to managing the contents of pam files?  For instance, why does pam_d_sshd use templates versus the way pam_password_\* manages arrays of lines?  Was it a goal to be able to composite file contents?  The latter supports that kindof, whereas the former doesn't.

**Comment by ghoneycutt** [comment]
We have released a new major version of this module and greatly appreciate your efforts. Please consider using the new version which supports Puppet 5 and 6.
