### ISSUE TITLE
dash before the session for pam.d/login template

### ISSUE THREAD

**Issue by bturng** [ghoneycutt/puppet-module-pam#145]
I noticed that there is a dash before the session for pam.d/login template

I went through the pam documentation and could not find why a dash is needed

can you advise if this needs to be removed . 

https://github.com/ghoneycutt/puppet-module-pam/blob/master/templates/login.el[67].erb
-session   optional     pam_ck_connector.so

**Comment by ghoneycutt** [comment]
Good question.. had to do some digging on that.

"If a line in the configuration file starts with a dash, the error isn't logged.  This can be useful for modules that may not be present, for example, a module for fingerprint authentication may not be present, but if it is, it should be used."

http://wpollock.com/AUnix2/PAM-Help.htm
