### ISSUE TITLE
Basic usage

### ISSUE THREAD

**Issue by craigcarnell** [ghoneycutt/puppet-module-pam#146]
Hi,

I am trying to add the following:

add session required pam_limits.so in:

    /etc/pam.d/common-session
    /etc/pam.d/common-session-noninteractive if the file exists
    /etc/pam.d/sshd if you access the machine via SSH

How can I do this via the plugin?

**Comment by ghoneycutt** [comment]
Look for the params that end in `_lines`. Those each take an array of lines for the contents of the file that they manage.
