### ISSUE TITLE
CentOS 7: password-auth-ac changed incorrectly

### ISSUE THREAD

**Issue by poikilotherm** [ghoneycutt/puppet-module-pam#166]
Hey guys,

running on CentOS 7, due to https://github.com/ghoneycutt/puppet-module-pam/blob/8a88b37e43bb897108797ed027ea41d6a05240f0/manifests/init.pp#L442 the pam_unix.so hash alogrithm is changed from system default sha512 to insecure md5.

Shall I create a pull request to provide a fix (maybe other parts are affected, too)?

Cheers
Poikilotherm

**Comment by ghoneycutt** [comment]
Many thanks!

**Comment by ghoneycutt** [comment]
Please do!

**Comment by ghoneycutt** [comment]
Resolved by PR #196

**Comment by ghoneycutt** [comment]
Released in v3.2.0
