### ISSUE TITLE
Puppet5 and 6 compatibility

### ISSUE THREAD

**Issue by treydock** [ghoneycutt/puppet-module-pam#168]
Place to discuss changes for next major release that will introduce puppet5 compatibility. We are working against the `puppet5` branch. https://github.com/ghoneycutt/puppet-module-pam/tree/puppet5

- [x] Remove VAS logic and move to examples
- [x] Use module hiera data
- [x] use new readme format  (https://github.com/ghoneycutt/puppet-module-bind/blob/master/README.md)
- [x] Phil to sign off on spec testing
- [x] Get rid of lsb* facts (Thanks to @v4ld3r5 for doing these for Suse. We'll need to ensure they are all gone)
- [x] stop depending on ghoneycutt/common (need to migrate mkdir_p to its own module, though just using an exec here first is OK so we don't have another dependency to wait on)
- [x] switch to use trlinking/nsswitch since it is Puppet Approved
- [x] nsswitch supports puppet v5 (https://github.com/trlinkin/puppet-nsswitch/pull/27)
- [x] use newer readme format that is needed for Approved status - PR #189
- [x] @ghoneycutt Can you please rebase puppet5 branch with master to get examples directory created.
- [x] replace `create_resources()` - PR #190
- [x] Phil to sign off that the new version works in his environment

**Comment by ghoneycutt** [comment]
Rebased. Had to force push, so hope it doesnt mess up your branches.

**Comment by ghoneycutt** [comment]
cc @Phil-Friderici

**Comment by treydock** [comment]
@ghoneycutt I have hiera5 changes staged. I'll rebase and open PR in coming days.

**Comment by ArVincentr** [comment]
Seems since  Facter 2.2 some changes were made to lsbmajdistrelease as per https://docs.puppet.com/facter/2.2/release_notes.html#significant-changes-to-existing-facts

would it be possible to use "operatingsystemmajrelease" for the puppet 5 release and facter 3.x ?  
fact doens't return anything on SLES systems.

Regards

**Comment by treydock** [comment]
@ghoneycutt Would you be open to idea of switching to https://forge.puppet.com/trlinkin/nsswitch for nsswitch dependency?  Or making the dependency something a site has to add if they choose to set `manage_nsswitch` to true.  Would be a non issue if I could find a way to make puppet not tell me about missing dependencies without suppressing all warnings:

```
Warning: ModuleLoader: module 'pam' has unresolved dependencies - it will only see those that are resolved. Use 'puppet module list --tree' to see information about modules
   (file & line not available)
```

```
├─┬ ghoneycutt-pam (v2.33.0)
│ ├── UNMET DEPENDENCY ghoneycutt-nsswitch (>= 1.3.0 < 2.0.0)
│ └── ghoneycutt-common (v1.5.0)
```

**Comment by ghoneycutt** [comment]
We can switch to Tom's module since it is approved. We'll need to do some work on it, specifically the lack of spec tests.

**Comment by Phil-Friderici** [comment]
Added some refactoring for the common* files in https://github.com/ghoneycutt/puppet-module-pam/pull/172.

**Comment by Phil-Friderici** [comment]
Converted the README to `new readme format` in https://github.com/ghoneycutt/puppet-module-pam/pull/174

**Comment by Phil-Friderici** [comment]
Will work on refactors for code and spec tests in https://github.com/ghoneycutt/puppet-module-pam/pull/175

**Comment by ghoneycutt** [comment]
waiting on https://github.com/trlinkin/puppet-nsswitch/pull/27 https://tickets.puppetlabs.com/browse/MODULES-7084

**Comment by ghoneycutt** [comment]
Will merge from https://github.com/ghoneycutt/puppet-module-pam/pull/179
