### ISSUE TITLE
allowed_users ordering

### ISSUE THREAD

**Issue by kwilcox77** [ghoneycutt/puppet-module-pam#184]
Hello,

When I pass a hash through to the allowed_users parameter, it reorders my entries before putting them in the access.conf file.  I think they may be ordered alphabetically.

This means that my access rule for root is after my lines for ALL when it should be first.

According to the man page for access.conf, ordering is important as permissions are granted on the first pattern match.

Thanks for your time!

**Comment by ghoneycutt** [comment]
Is this still an issue with the new version?

**Comment by ghoneycutt** [comment]
This should not matter in practice because all user/groups being allowed are listed before the default deny, which denies everything else.
