### ISSUE TITLE
pam_d_login_oracle_options not available for el7

### ISSUE THREAD

**Issue by hdep** [ghoneycutt/puppet-module-pam#197]
Hello,

my DBA needs to add the following lines : 
/etc/pam.d/login
session    required     pam_limits.so

I read the code, there is the following option avalaible : 
pam_d_login_oracle_options

But this is only for el5. 
Of course I'm running el7  :) 

Can I propose a PR for changing the el7 templates or is there a reason for not having this option ? 

Thank you

**Comment by ghoneycutt** [comment]
Please do!
