### ISSUE TITLE
Add support for SLES 15

### ISSUE THREAD

**Issue by ph84172** [ghoneycutt/puppet-module-pam#210]
Just starting to migrate our SLES 12 systems to SLES 15 which isn't currently supported by this module.

Unless you're working on it now and an update is imminent I can do some testing of this module on 15; it doesn't look as if much has changed from a PAM perspective.

Thanks.

**Comment by ghoneycutt** [comment]
@ph84172 I'm having a hard time getting sles15 going with vagrant as I'm using a minimal install and believe I don't have all the necessary repositories.

```
suse15-pam:~ # zypper repos
Repository priorities are without effect. All enabled repositories share the same priority.

# | Alias          | Name                                 | Enabled | GPG Check | Refresh
--+----------------+--------------------------------------+---------+-----------+--------
1 | SLES15-15-0    | SLES15-15-0                          | Yes     | (r ) Yes  | No
2 | puppet5        | Puppet 5 Repository sles 15 - x86_64 | Yes     | (r ) Yes  | No
3 | puppet5-source | Puppet 5 Repository sles 15 - Source | No      | ----      | ----
```

The number of packages in the suse repo seems extremely low

```
suse15-pam:~ # zypper search -i -r SLES15-15-0| wc -l
```

Do you know of a repo URL that would have the rest of the packages? Without that, I can't get the puppet-agent installed.

**Comment by ph84172** [comment]
@ghoneycutt hmm that's odd - my fresh install is showing 330 packages in SLES15-15-0.  Have you done a "zypper update"?

**Comment by ghoneycutt** [comment]
SLES15 cannot be formally supported by us until we have acceptance tests and vagrant working.
