### ISSUE TITLE
RHEL8 support

### ISSUE THREAD

**Issue by term1n4l** [ghoneycutt/puppet-module-pam#211]
Could you update this module to allow support for RHEL8?

**Comment by ghoneycutt** [comment]
Please send a pull request. Here's a recent example of SLES 15 being added.

https://github.com/ghoneycutt/puppet-module-pam/commit/f87a27a9d86981efd1a93b553df1c3f511b28ea7

**Comment by term1n4l** [comment]
> Please send a pull request. Here's a recent example of SLES 15 being added.
> 
> [f87a27a](https://github.com/ghoneycutt/puppet-module-pam/commit/f87a27a9d86981efd1a93b553df1c3f511b28ea7)

Seems Pete Harvey beat me to it, thanks Pete Harvey :+1:

**Comment by marszip** [comment]
When do expect to have a formal release that includes this fix?

**Comment by ghoneycutt** [comment]
Released in v3.4.0 !
