### ISSUE TITLE
Amazon Linux 2 support

### ISSUE THREAD

**Issue by jhhayden** [ghoneycutt/puppet-module-pam#214]
Is there any plans to add Amazon Linux 2 to the list of support OS's?

**Comment by ghoneycutt** [comment]
If you want to take a crack at it, I'm happy to help you. Checkout https://github.com/ghoneycutt/puppet-module-pam/commit/f87a27a9d86981efd1a93b553df1c3f511b28ea7

You'll need to get a vanilla image and get the data from that.

**Comment by mears148** [comment]
I took a stab at this. Just need help on the travis acceptance testing part. I have created a pull request to get this implemented. Strange how I have yet to find a module with Amazon Linux support, considering the popularity of the platform.

**Comment by ghoneycutt** [comment]
This has been added in v3.10.0
