### ISSUE TITLE
pam_access.so for RHEL 8

### ISSUE THREAD

**Issue by mjbedynek** [ghoneycutt/puppet-module-pam#223]
Hi,

I just wanted to report a difference in your module.  It doesn't have a section for pam_access in the RHEL 8 template:

puppet-module-pam/templates/login.el7.erb
<% if @login_pam_access != 'absent' -%>
account    <%= @login_pam_access %>     pam_access.so
<% end -%>

puppet-module-pam/templates/sshd.el7.erb
<% if @sshd_pam_access != 'absent' -%>
account    <%= @sshd_pam_access %>     pam_access.so
<% end -%>

This feature was enabled on our RHEL 7 hosts but we noticed it broken on the RHEL 8 hosts.

Matt

**Comment by ghoneycutt** [comment]
We now support RHEL8. Please re-open if this is still an issue.
