### ISSUE TITLE
Using access_conf_template parameter

### ISSUE THREAD

**Issue by mp05** [ghoneycutt/puppet-module-pam#236]
I am trying to set the template path for the access.conf template, I see there is a parameter access_conf_template for the pam::accesslogin class but I can only seem to use this parameter by setting it through Heira and as the pam module already includes the pam::accesslogin I cannot use this class again directly in order to add this parameter.

Is there a way of setting the access_conf_template parameter apart from using Heira

**Comment by ghoneycutt** [comment]
Nope. Embrace Hiera :)
