### ISSUE TITLE
Is it possible to only touch files that are explict defined?

### ISSUE THREAD

**Issue by bufferoverflow** [ghoneycutt/puppet-module-pam#240]
I would like to change only the `/etc/pam.d/common-auth` and maybe later other files. However, the module is touching all the files instead. Is there an easy way to achieve that? Especially for client machines I prefer to only touch the files we have to change.

**Comment by bschonec** [comment]
+1 to that.

I'd like a feature addition to allow only modifying the limits.d files while I "work up" to managing the /etc/pam.d files.  Right now it's all or nothing and I've broken more than a few servers by pushing out the wrong /etc/pam.d/ settings.

**Comment by bschonec** [comment]
Here's [something](https://github.com/bschonec/puppet-module-pam/tree/suppress_running_of_selected_modules) that I'm working on that attempts to provide this functionality.

**Comment by ghoneycutt** [comment]
We are not interested in putting in the effort to add a `manage_` parameter for every file this module touches as the normal use case is to embrace the module in its totality. You could override this in a profile with things like

```puppet
File <| title == 'common_ac-or-whatever' |> {
  replace => false,
}
```
